// #import "@preview/typsy:0.2.5": *
// #import "my-class.typ": *

#let epsilon-for-float = 1e-14
// Tolerance allowed for data generated by the algorithm.
#let epsilon-for-algo = 1e-6

// Some data types
#let Union(..args) = {
  assert.eq(args.named().len(), 0, message: "Named arguments are not supported.")
  args.pos()
}
#let (Int, Float, Decimal, Length, Angle, None, Bool, Str, Content, Array, Function, Stroke) = (
  int,
  float,
  decimal,
  length,
  angle,
  none,
  bool,
  str,
  content,
  array,
  function,
  stroke,
)
#let Numeric = Union(Int, Float, Decimal)


// geometric granularity
#let Geom-granularity(max-dist: Length, max-angle: Angle, min-dist: Length) = {
  (
    tag: "Geom-granularity",
    // Accepted if min-dist < dist < max-dist and angle < max-angle. This is the standard geometric constraint.
    // Accepted if dist < min-dist. Used to avoid oversampling at oscillation discontinuities.
    // Otherwise rejected.
    max-dist: max-dist,
    max-angle: max-angle, // 一定要是锐角
    min-dist: min-dist,
    get-factors: self => (
      max-dist-factor: {
        // assert.eq(self.max-dist.em, 0.0, message: "Relative length is not supported.")
        // calc.pow(self.max-dist.pt(), 2)
        calc.pow(self.max-dist, 2)
      },
      angle-factor: calc.tan(self.max-angle),
      min-dist-factor: {
        // assert.eq(self.min-dist.em, 0.0, message: "Relative length is not supported.")
        // calc.pow(self.min-dist.pt(), 2)
        calc.pow(self.min-dist, 2)
      },
    ),
  )
}

#let Coord(x: Numeric, y: Numeric) = (
  tag: "Coord",
  x: x,
  y: y,
  is-zero: self => {
    // No need to introduce `epsilon`, because only `prev-vec` is initially a zero vector, and its zeros are directly assigned rather than computed.
    return self.x == 0 and self.y == 0
  },
)

#let Point(x: Numeric, y: Numeric, t: Union(Numeric, None)) = (
  tag: "Point",
  x: x,
  y: y,
  // 'none' indicates this value is not applicable. Used in the `clip` function: clipping is based on x and y, so if clipping occurs, t becomes meaningless.
  t: t,
)

// 所有参数都是纯数值或者 float.inf ，不允许 none 之类的
#let Rect(x-min: none, x-max: none, y-min: none, y-max: none) = {
  import float: inf
  // assert.eq(type(x-min), Numeric)
  if x-min > x-max {
    // empty set
    x-min = +inf
    x-max = -inf
  }
  if y-min > y-max {
    // empty set
    y-min = +inf
    y-max = -inf
  }
  return (
    x-min: x-min,
    x-max: x-max,
    y-min: y-min,
    y-max: y-max,
    x: (x-min, x-max),
    y: (y-min, y-max),
  )
}

#let Axes(x: none, y: none) = {
  return (
    x: x,
    y: y,
  )
}

#let corners-to-rect = Rect
#let axes-to-rect(axes) = {
  let (x, y) = axes
  let (x-min, x-max) = x
  let (y-min, y-max) = y
  Rect(x-min: x-min, x-max: x-max, y-min: y-min, y-max: y-max)
}

#let Element(bounds: Rect, render: Function) = {
  return (
    bounds: bounds,
    render: render,
    // render: ctx => drawable
    // ctx: (viewport, length)
  )
}

#let Interval(left: Point, right: Point, accepted: Bool, off-view: Bool) = {
  (
    left: left,
    right: right,
    accepted: accepted,
    off-view: off-view,
  )
}

#let dims = ("x", "y")

// #start geom-presets
/// Geometric granularity presets
#let geom-presets = {
  (
    balanced: Geom-granularity(
      max-dist: 0.5,
      max-angle: 5deg,
      min-dist: 0.05,
    ),
    fine: Geom-granularity(
      max-dist: 0.03,
      max-angle: 1deg,
      min-dist: 0.005,
    ),
    coarse: Geom-granularity(
      max-dist: 5,
      max-angle: 10deg,
      min-dist: 0.5,
    ),
    // Use this to generate scatter plot
    pointwise: Geom-granularity(
      max-dist: 0,
      max-angle: 0deg,
      min-dist: 0,
    ),
    // Use this to generate a line chart. Note that `max-depth` has no effect in this case, as no subdivision will ever occur.
    polyline: Geom-granularity(
      max-dist: float.inf,
      max-angle: 89deg,
      min-dist: float.inf,
    ),
  )
}
// #end geom-presets

#let point-to-coord(point) = Coord(x: point.x, y: point.y)

#let coord-to-point(coord) = Point(x: coord.x, y: coord.y, t: none)

#let vec-from-to(from, to) = {
  Coord(x: to.x - from.x, y: to.y - from.y)
}

#let zero-vec = Coord(x: 0, y: 0)

// import float.inf
#let inf = float.inf
#let empty-range = (+inf, -inf)
#let full-range = (-inf, +inf)
#let empty-rect = axes-to-rect(Axes(x: empty-range, y: empty-range))
#let full-rect = axes-to-rect(Axes(x: full-range, y: full-range))
